- name: Router to wlan access point
  hosts: all
  vars_files: common.yml 
  become: yes
  tasks:
  - apt: 
      pkg:
      - dnsmasq
      - dhcpcd
      - ufw
      - ntp
  - ufw:
      rule: allow
      src: '{{ufw_allow_from}}'
  - ufw:
      rule: allow
      src: '{{wg_ip_range}}'
  - ufw:
      rule: allow
      direction: in
      interface: eth0
  - ufw:
      rule: allow
      direction: out
      interface: eth0
  - ufw:
      rule: allow
      direction: in
      src: '{{lan_ip}}/24'
  - ufw:
      rule: allow
      direction: in
      src: '{{router_ip}}/24'
  - ufw:
      state: enabled
  - ansible.builtin.blockinfile:
      path: /etc/dhcpcd.conf
      block: |
        interface eth0
            static ip_address={{lan_ip}}/24
  - ansible.builtin.copy:
      src: "etc/network/interfaces.d/wlan0"
      dest: "/etc/network/interfaces.d/"
      owner: root
      group: root
  - ansible.builtin.copy:
      src: etc/dnsmasq.d/router.conf
      dest: /etc/dnsmasq.d/router.conf
      owner: root
      group: root
  - name: Use nearby NTP servers
    ansible.builtin.replace:
      path: /etc/ntp.conf
      regexp: '^pool (\d).debian.pool.ntp.org iburst$'
      replace: 'pool \1.fi.pool.ntp.org iburst'
  - name: Restart ntp
    ansible.builtin.systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: ntp
  - name: Enable ip forward
    ansible.builtin.lineinfile:
      path: /etc/ufw/sysctl.conf
      regexp: "^#net.ipv4.ip_forward=1"
      line: "net.ipv4.ip_forward=1"
  - name: Enable ipv6 forward
    ansible.builtin.lineinfile:
      path: /etc/ufw/sysctl.conf
      regexp: "^#net/ipv6/conf/default/forwarding=1"
      line: "net/ipv6/conf/default/forwarding=1"
  - name: Enable packet forwarding in ufw
    ansible.builtin.lineinfile:
      path: /etc/default/ufw
      regexp: "^DEFAULT_FORWARD_POLICY=\"DROP\""
      line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""
  - name: Add nat table rules
    ansible.builtin.blockinfile:
      path: /etc/ufw/before.rules
      block: |
        # nat Table rules
        *nat
        :POSTROUTING ACCEPT [0:0]

        # Forward traffic from eth0 through wwan0.
        -A POSTROUTING -s {{router_ip}}/24 -o wwan0 -j MASQUERADE

        # don't delete the 'COMMIT' line or these nat table rules won't be processed
        COMMIT
      insertbefore: "# Don't delete these required lines, otherwise there will be errors"

#sudo iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE  
#$ sudo iptables -A FORWARD -i wwan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT  
#$ sudo iptables -A FORWARD -i eth0 -o wwan0 -j ACCEPT

