- name: setup custom scripts
  hosts: all
  tasks:
  - ansible.builtin.pip:
      name:
      - python-dateutil
  - ansible.builtin.copy:
      src: "home/pi/sensors/vattenfall/vattenfall.py"
      dest: /home/pi/sensors/vattenfall/
      owner: pi
      group: pi
      mode: '755'
  - ansible.builtin.cron:
      name: vattenfall
      minute: "0"
      hour: "12"
      user: pi
      job: "/home/pi/sensors/vattenfall/vattenfall.py >> /home/pi/sensors/vattenfall/output.log"